<a href="https://colab.research.google.com/github/ZoubirCHATTI/02__Probability-Statisitics/blob/main/01_Basis%20statistics/03_Power_of_z_score.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [51]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [52]:
path="https://raw.githubusercontent.com/ZoubirCHATTI/02__Probability-Statisitics/main/01_Basis%20statistics/data/powerconsumption.csv"
df=pd.read_csv(path)

In [53]:
df.head()

,Datetime,Temperature,Humidity,WindSpeed,GeneralDiffuseFlows,DiffuseFlows,PowerConsumption_Zone1,PowerConsumption_Zone2,PowerConsumption_Zone3
0,1/1/2017 0:00,6.559,73.8,0.083,0.051,0.119,34055.69620,16128.87538,20240.96386
1,1/1/2017 0:10,6.414,74.5,0.083,0.070,0.085,29814.68354,19375.07599,20131.08434
2,1/1/2017 0:20,6.313,74.5,0.080,0.062,0.100,29128.10127,19006.68693,19668.43373
3,1/1/2017 0:30,6.121,75.0,0.083,0.091,0.096,28228.86076,18361.09422,18899.27711
4,1/1/2017 0:40,5.921,75.7,0.081,0.048,0.085,27335.69620,17872.34043,18442.40964

In [54]:
df.isnull().sum()

Datetime                  0
Temperature               0
Humidity                  0
WindSpeed                 0
GeneralDiffuseFlows       0
DiffuseFlows              0
PowerConsumption_Zone1    0
PowerConsumption_Zone2    0
PowerConsumption_Zone3    0
dtype: int64

In [55]:
df.describe()

,Temperature,Humidity,WindSpeed,GeneralDiffuseFlows,DiffuseFlows,PowerConsumption_Zone1,PowerConsumption_Zone2,PowerConsumption_Zone3
count,52416.000000,52416.000000,52416.000000,52416.000000,52416.000000,52416.000000,52416.000000,52416.000000
mean,18.810024,68.259518,1.959489,182.696614,75.028022,32344.970564,21042.509082,17835.406218
std,5.815476,15.551177,2.348862,264.400960,124.210949,7130.562564,5201.465892,6622.165099
min,3.247000,11.340000,0.050000,0.004000,0.011000,13895.696200,8560.081466,5935.174070
25%,14.410000,58.310000,0.078000,0.062000,0.122000,26310.668692,16980.766032,13129.326630
50%,18.780000,69.860000,0.086000,5.035500,4.456000,32265.920340,20823.168405,16415.117470
75%,22.890000,81.400000,4.915000,319.600000,101.000000,37309.018185,24713.717520,21624.100420
max,40.010000,94.800000,6.483000,1163.000000,936.000000,52204.395120,37408.860760,47598.326360

In [ ]:
z_consommation_zone1=(df['PowerConsumption_Zone1']-df['PowerConsumption_Zone1'].mean())/df['PowerConsumption_Zone1'].std()

In [ ]:
plt.figure(figsize=(15, 5))
plt.plot(z_consommation_zone1)
plt.xlabel('date index')
plt.ylabel('average consumption')
plt.title('Average electricity consumption zone one')
plt.axhline(y=3, color='r', lw=3)
plt.axhline(y=-3, color='r', lw=3)
plt.grid(True)

In [ ]:
z_consommation_zone2=(df['PowerConsumption_Zone2']-df['PowerConsumption_Zone2'].mean())/df['PowerConsumption_Zone2'].std()

In [ ]:
plt.figure(figsize=(15, 5))
plt.plot(z_consommation_zone2)
plt.xlabel('date index')
plt.ylabel('average consumption per site')
plt.title('Average electricity consumption zone two')
plt.axhline(y=3, color='r', lw=3)
plt.axhline(y=-3, color='r', lw=3)
plt.grid(True)

In [ ]:
z_consommation_zone3=(df['PowerConsumption_Zone3']-df['PowerConsumption_Zone3'].mean())/df['PowerConsumption_Zone3'].std()

In [ ]:
plt.figure(figsize=(15, 5))
plt.plot(z_consommation_zone3)
plt.xlabel('date index')
plt.ylabel('average consumption')
plt.title('Average electricity consumption zone three')
plt.axhline(y=3, color='r', lw=3)
plt.axhline(y=-3, color='r', lw=3)
plt.grid(True)